[package]
name = "resharper-annotate"
version = "0.2.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.151" }
serde_derive = { version = "1.0.147" }
serde-xml-rs = { version = "0.6.0" }
